repos:
  - repo: local
    hooks:
      - id: check-copyright
        name: Check copyright headers
        entry: python bin/check_copyright.py
        types: [python]
        language: python
        pass_filenames: true
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        exclude: ^demo/notebooks/.*
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
        name: Run ruff check
        entry: ruff check --force-exclude --fix
        pass_filenames: true
  - repo: "https://github.com/psf/black"
    rev: 24.3.0
    hooks:
      - id: black
        name: Run black check
        entry: black
        args: ["--check"]
        exclude: ^bin/
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        name: Run prettier
        args: ["--log-level", "error"]
        exclude: ".*json$"
