---
blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ General Question"
    url: https://github.com/SonyResearch/fhibe_evaluation_api/discussions/categories/q-a
    about: Please ask or answer questions as a discussion thread
