name: Run pytest and coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Echo branch name
        run: echo "Running on branch $GITHUB_REF_NAME"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Run tests and coverage
        run: |
          poetry run pytest -s tests/test_percentage_correct_keypoints
          # poetry run coverage run --source=fhibe_eval_api/ -m pytest -s tests 
          # poetry run coverage report
          # poetry run coverage xml -o coverage.xml
          # COVERAGE_THRESHOLD=70
          # coverage_percentage=$(poetry run coverage report | awk '/^TOTAL/ { print $NF }' | tr -d '%')
          # if [ "$coverage_percentage" -lt "$COVERAGE_THRESHOLD" ]; then
          #   echo "Fail: Coverage threshold ($COVERAGE_THRESHOLD%) not met. Coverage percentage: $coverage_percentage%"
          #   exit 1
          # else
          #   echo "Success: Coverage threshold ($COVERAGE_THRESHOLD%) met. Coverage percentage: $coverage_percentage%"
          # fi
        shell: bash
